### ISSUE TITLE
[FATAL] Could not initialize SDL2!

### ISSUE THREAD

**Issue by reduz** [hukkax/Propulse#2]
```
Propulse Tracker 0.9.5.5 starting...
Loading configuration...
Setting up video...
SDL loaded from /home/xxxx/src/Propulse/libSDL2-2.0.so.0
[FATAL] Could not initialize SDL2!
Closing down...
```

**Comment by hukkax** [comment]
I had this occur a while ago when testing on a different PC (Linux Mint). I can't recall how I fixed it (might've been simply renaming the .so), will look into it once I have access to the PC again later this week.

**Comment by hukkax** [comment]
The Propulse binary now has the RPATH set so that it should find libraries from either its root directory or any of the standard library paths.

**Comment by michaelsjackson** [comment]
Hmm, having same error here, ubuntu 16.04 LTS. Here my error message:

> 
> TSDL2Library: Could not load "/home/you/Downloads/propulse-0960-linux-x64/libSDL2-2.0.so.0" library
> [FATAL] Could not initialize SDL2!

**Comment by michaelsjackson** [comment]
I tried renaming libSDL2-2.0.so.0 to a few variants, without any difference, still same error.  But not a big problem here, just mentioning here, the only reason I tested it was because it could "in theory" work directly in linux, I can still use within wine various other packages, but always good having direct linux versions, if they would work.

**Comment by hukkax** [comment]
Can you paste the output of "ldd ./Propulse"? As a last resort you could move the .so files to /usr/lib/.

**Comment by michaelsjackson** [comment]
```
~/Downloads/propulse-0960-linux-x64$ ldd ./Propulse 
	linux-vdso.so.1 =>  (0x00007ffddebf9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fda09e7d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fda09c79000)
	libsoxr.so.0 => /usr/lib/x86_64-linux-gnu/libsoxr.so.0 (0x00007fda09a14000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fda0964a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fda0a09a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fda09341000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fda0911f000)

```

**Comment by hukkax** [comment]
Just realized you're trying to run the 0.9.6.0 binary - which is from before I started setting the RPATH in the executable. That would explain why it's not even attempting to load the libraries from the binary's path.
Moving the .so files to /usr/lib/x86_64-linux-gnu/ should fix the issue, or you could grab the newer binaries from https://github.com/hukkax/Propulse/tree/trunk/bin/linux-64bit.

**Comment by michaelsjackson** [comment]
It did not work, gave another error, so I gave up, for now. No problem.  Thanks for your help.
