### ISSUE TITLE
Error compiling on MacOS 64

### ISSUE THREAD

**Issue by circular17** [hukkax/Propulse#5]
Hi! I get the following error while trying to compile on macOS Catalina.

```
ld: library not found for -lX11
An error occurred while linking 
```

**Comment by hukkax** [comment]
Afraid I can't help you there, I don't have a Mac and am not familiar with them. The file docs/building.txt has 3rd-party contributed build instructions for MacOS, however.

**Comment by circular17** [comment]
I did not find anything about X11 in the building.txt file. Though I found that X11 is not available anymore by default on MacOS and that you need to install XQuartz: https://www.xquartz.org

I did that, and now linker complains that it cannot find _SDL_* for architecture x86_64.
