### ISSUE TITLE
Error compiling on Linux 64

### ISSUE THREAD

**Issue by circular17** [hukkax/Propulse#6]
The linker says it needs the libraries SDL2, soxr and bass.

I've got SDL2 and soxr by installed the packages: libsdl2-dev libsoxr-dev

Cannot find however bass. The command `dpkg -S libbass.so` gives no result.

**Comment by hukkax** [comment]
Have a look at docs/building.txt, it lists the dependencies and where to get them. Alternatively build without BASS.

**Comment by circular17** [comment]
I've been able to download BASS from this website: https://www.freebasic.net/forum/viewtopic.php?t=23394

So now I compiled with BASS. However I get a runtime error on a divss instruction (call to SDL by TWindow.FlipFrame).

**Comment by hukkax** [comment]
That build of BASS is 5 years old. Better use the one from un4seen directly or the .so in bin/Linux-64bit.

I was able to reproduce the crash. Seems to happen in the SDL_RenderClear call, which fortunately isn't required for proper function so a temporary fix would be to simply comment out that call.
